language: php

sudo: false

env:
  global:
    - COMPOSER_NO_INTERACTION="1"

matrix:
    include:
      - php: 7.0
        env: COMPOSER_ARGS=""
      - php: 7.1
        env: COMPOSER_ARGS=""
      - php: 7.2
        env: COMPOSER_ARGS=""
      - php: "8.0"
        env: COMPOSER_ARGS=""

      - php: 7.0
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 7.1
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 7.2
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 8.0
        env: COMPOSER_ARGS="--prefer-lowest"

cache:
    directories:
      - $HOME/.composer/cache

install:
    - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS

before_script:
    - phpenv config-rm xdebug.ini || true
    - bash -c "composer update $COMPOSER_ARGS"

script:
    - vendor/bin/phpunit
